version: '3.8'

services:
    db:
        image: mysql:8.0
        container_name: db
        environment:
            MYSQL_ROOT_PASSWORD: root
            MYSQL_DATABASE: laravel
            MYSQL_USER: laravel
            MYSQL_PASSWORD: laravel
        volumes:
            - dbdata:/var/lib/mysql
            - ./docker/mysql/my.cnf:/etc/mysql/my.cnf
        networks:
            laravel:
                ipv4_address: 172.20.0.2

    web:
        image: nginx:latest
        container_name: web
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/nginx/conf.d:/etc/nginx/conf.d
        ports:
            - "30080:80"
        networks:
            laravel:
                ipv4_address: 172.20.0.3
        depends_on:
            - app

    app:
        build:
            context: .
            dockerfile: docker/php/Dockerfile
        container_name: app
        working_dir: /var/www
        volumes:
            - .:/var/www
            - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
        networks:
            laravel:
                ipv4_address: 172.20.0.4
        environment:
            - DB_HOST=db
            - DB_PORT=3306
            - DB_DATABASE=laravel
            - DB_USERNAME=laravel
            - DB_PASSWORD=laravel
        depends_on:
            - db
            - redis

    redis:
        image: redis:latest
        container_name: redis
        networks:
            laravel:
                ipv4_address: 172.20.0.5

networks:
    laravel:
        driver: bridge
        ipam:
            config:
                - subnet: 172.20.0.0/16

volumes:
    dbdata: